{% set name = "adversarial-robustness-toolbox" %}
{% set version = "1.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 28fcd4f555c3e41c9b63a9d939dcbb902d7f4d739ddd99828b701b15a8f97903

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - cma
    - ffmpeg-python
    - matplotlib-base
    - mypy
    - pillow
    - pydub
    - kornia
    - python
    - resampy
    - scikit-learn ==0.22.1
    - scipy ==1.4.1
    - six
    - statsmodels
    - tqdm
    - tensorflow

test:
  imports:
    - art
    - art.attacks
    - art.attacks.evasion
    - art.attacks.evasion.adversarial_patch
    - art.attacks.evasion.projected_gradient_descent
    - art.attacks.extraction
    - art.attacks.inference
    - art.attacks.poisoning
    - art.attacks.poisoning.perturbations
    - art.classifiers
    - art.classifiers.scikitlearn
    - art.defences
    - art.defences.detector
    - art.defences.detector.evasion
    - art.defences.detector.evasion.subsetscanning
    - art.defences.detector.poison
    - art.defences.postprocessor
    - art.defences.preprocessor
    - art.defences.trainer
    - art.defences.transformer
    - art.estimators
    - art.estimators.certification
    - art.estimators.certification.randomized_smoothing
    - art.estimators.classification
    - art.estimators.encoding
    - art.estimators.generation
    - art.estimators.object_detection
    - art.estimators.regression
    - art.metrics
    - art.wrappers
    - tests
    - tests.attacks
    - tests.attacks.evasion
    - tests.attacks.inference
    - tests.classifiersFrameworks
    - tests.defences
    - tests.defences.detector
    - tests.defences.detector.evasion
    - tests.defences.detector.evasion.subsetscanning
    - tests.defences.detector.poison
    - tests.estimators
    - tests.estimators.certification
    - tests.estimators.classification
    - tests.metrics
    - tests.wrappers

about:
  home: https://github.com/Trusted-AI/adversarial-robustness-toolbox
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Toolbox for adversarial machine learning.
  doc_url: https://github.com/Trusted-AI/adversarial-robustness-toolbox/wiki/Documentation
  dev_url: https://github.com/Trusted-AI/adversarial-robustness-toolbox

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - oblute
    - ndmaxar
